Repository apache/ambari-logsearch, pull requests merged in 2018-11, with the labels that each got.

#20 AMBARI-24875. Log Search: cannot build sub-modules separately.
  .gitignore
  pom.xml
Labels: bug

#18 AMBARI-24847 - Logsearch: Cannot search for a term that includes spaces or dashes
  ambari-logsearch-it/pom.xml
  ambari-logsearch-it/src/test/java/org/apache/ambari/logsearch/solr/Solr.java
  ambari-logsearch-it/src/test/java/org/apache/ambari/logsearch/solr/SolrDocumentMatcher.java
  ambari-logsearch-it/src/test/java/org/apache/ambari/logsearch/solr/search/SearchServiceLogsTest.java
  ambari-logsearch-server/src/main/configsets/audit_logs/conf/managed-schema
  ambari-logsearch-server/src/main/configsets/hadoop_logs/conf/managed-schema
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/converter/AbstractDateRangeFacetQueryConverter.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/converter/AbstractOperationHolderConverter.java
  ambari-logsearch-web/src/app/services/logs-filtering-utils.service.ts
Labels: bug

#19 AMBARI-24833. Re-implement S3/HDFS outputs as global cloud outputs
  ambari-logsearch-logfeeder-plugin-api/src/main/java/org/apache/ambari/logfeeder/plugin/input/Input.java
  ambari-logsearch-logfeeder-plugin-api/src/main/java/org/apache/ambari/logfeeder/plugin/manager/OutputManager.java
  ambari-logsearch-logfeeder-plugin-api/src/main/java/org/apache/ambari/logfeeder/plugin/output/Output.java
  ambari-logsearch-logfeeder/pom.xml
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/common/LogFeederConstants.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/CloudStorageDestination.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/LogFeederProps.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/output/BucketConfig.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/output/CloudStorageOutputConfig.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/output/HdfsOutputConfig.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/output/OutputConfig.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/output/RolloverConfig.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/output/S3OutputConfig.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/credential/PlainTextSecretStore.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/input/InputS3File.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputHDFSFile.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputS3File.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/S3LogPathResolver.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/S3OutputConfiguration.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/S3Uploader.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageLoggerFactory.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageOutput.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageOutputManager.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageUploader.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CustomTimeBasedTriggeringPolicy.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/HDFSOutput.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/AbstractCloudClient.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/HDFSS3UploadClient.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/HDFSUploadClient.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/S3UploadClient.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/SecretKeyPair.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/UploadClient.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/UploadClientFactory.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/spool/LogSpooler.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/spool/LogSpoolerContext.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/spool/LogSpoolerException.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/spool/RolloverCondition.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/spool/RolloverHandler.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/util/LogFeederHDFSUtil.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/util/S3Util.java
  ambari-logsearch-logfeeder/src/main/resources/alias_config.json
  ambari-logsearch-logfeeder/src/main/resources/logfeeder.properties
  ambari-logsearch-logfeeder/src/test/java/org/apache/ambari/logfeeder/output/OutputS3FileTest.java
  ambari-logsearch-logfeeder/src/test/java/org/apache/ambari/logfeeder/output/S3LogPathResolverTest.java
  ambari-logsearch-logfeeder/src/test/java/org/apache/ambari/logfeeder/output/S3UploaderTest.java
  ambari-logsearch-logfeeder/src/test/java/org/apache/ambari/logfeeder/output/spool/LogSpoolerTest.java
  ambari-logsearch-server/pom.xml
  docker/cloud-docker-compose.yml
  docker/test-config/logfeeder/logfeeder.properties
  pom.xml
Labels: enhancement

#23 [AMBARI-24891] [Log Serach UI] The Log Index Filter panel does not work
  ambari-logsearch-web/src/app/components/action-menu/action-menu.component.ts
  ambari-logsearch-web/src/app/components/filter-button/filter-button.component.ts
  ambari-logsearch-web/src/app/components/menu-button/menu-button.component.html
  ambari-logsearch-web/src/app/components/menu-button/menu-button.component.ts
  ambari-logsearch-web/src/app/modules/shared/components/dropdown-button/dropdown-button.component.html
  ambari-logsearch-web/src/app/modules/shared/components/dropdown-button/dropdown-button.component.ts
  ambari-logsearch-web/src/app/modules/shared/components/dropdown-list/dropdown-list.component.ts
  ambari-logsearch-web/src/app/modules/shared/components/filter-dropdown/filter-dropdown.component.ts
Labels: web

#24 [AMBARI-24899] [Log Search UI] Change capture countdown text
  ambari-logsearch-web/src/assets/i18n/en.json
Labels: web

#25 AMBARI-24833. Extend cloud log rolling options
  ambari-logsearch-logfeeder/pom.xml
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/common/LogFeederConstants.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/CloudStorageDestination.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/LogFeederProps.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/output/ExternalHdfsOutputConfig.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/output/RolloverConfig.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageLoggerFactory.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageUploader.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/ExternalHDFSUploadClient.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/HDFSUploadClient.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/UploadClientFactory.java
  ambari-logsearch-logfeeder/src/main/resources/logfeeder.properties
Labels: cleanup

#26 AMBARI-24833. Support for cloud logs to using filters + JSON output
  ambari-logsearch-config-local/src/main/java/org/apache/ambari/logsearch/config/local/LogSearchConfigLogFeederLocal.java
  ambari-logsearch-config-zookeeper/src/main/java/org/apache/ambari/logsearch/config/zookeeper/LogLevelFilterManagerZK.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/common/LogFeederConstants.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/LogFeederProps.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/manager/operations/impl/AbstractInputConfigHandler.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/manager/operations/impl/CloudStorageInputConfigHandler.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/manager/operations/impl/DefaultInputConfigHandler.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputLineEnricher.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputManagerImpl.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageLoggerFactory.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageOutputManager.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageUploader.java
  ambari-logsearch-logfeeder/src/main/resources/logfeeder.properties
Labels: enhancement

#27 AMBARI-24833. HDFS client kerberos support + small fixes
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/common/LogFeederConstants.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/LogFeederProps.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/output/HdfsOutputConfig.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/manager/operations/impl/AbstractInputConfigHandler.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/manager/operations/impl/CloudStorageInputConfigHandler.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/manager/operations/impl/DefaultInputConfigHandler.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputLineEnricher.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/ExternalHDFSUploadClient.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/HDFSUploadClient.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/UploadClientFactory.java
Labels: enhancement

#29 AMBARI-24833. Use clustername and hostname in cloud log archive dir
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageLoggerFactory.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageUploader.java
Labels: enhancement

#30 AMBARI-24833. Let logfeeder.properties override core-site configs.
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/HDFSS3UploadClient.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/HDFSUploadClient.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/util/LogFeederHDFSUtil.java
  ambari-logsearch-logfeeder/src/main/resources/logfeeder.properties
Labels: enhancement

#32 [AMBARI-24882] [Log Search UI] Change sticky filter panel solution from JS to clean css.
  ambari-logsearch-web/src/app/components/filters-panel/filters-panel.component.less
  ambari-logsearch-web/src/app/components/log-index-filter/log-index-filter.component.less
  ambari-logsearch-web/src/app/components/logs-container/logs-container.component.less
  ambari-logsearch-web/src/app/components/logs-container/logs-container.component.ts
  ambari-logsearch-web/src/app/modules/shared/components/dropdown-list/dropdown-list.component.less
Labels: web

#31 AMBARI-24928. Fix non-fatal POSTUN scriptlet failure + use different logfile for metrics
  ambari-logsearch-assembly/src/main/package/deb/logfeeder/postrm
  ambari-logsearch-assembly/src/main/package/deb/portal/postrm
  ambari-logsearch-assembly/src/main/package/rpm/logfeeder/postremove.sh
  ambari-logsearch-assembly/src/main/package/rpm/portal/postremove.sh
  ambari-logsearch-logfeeder-plugin-api/src/main/java/org/apache/ambari/logfeeder/plugin/common/ConfigItem.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/metrics/StatsLogger.java
  ambari-logsearch-logfeeder/src/main/resources/log4j2.yml
Labels: bug, enhancement

#33 AMBARI-24833. Do not open FS on main thread.
  ambari-logsearch-config-local/src/main/java/org/apache/ambari/logsearch/config/local/LogSearchConfigLogFeederLocal.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/common/LogFeederConstants.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/LogFeederProps.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageOutput.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageUploader.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/HDFSUploadClient.java
Labels: enhancement

#34 AMBARI-24932. Log Feeder: LB solr client - retry requests in case of errors
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputSolr.java
Labels: enhancement

#35 AMBARI-24935. Log Search: enable/disable request audit logging for jetty
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/conf/LogSearchHttpConfig.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/conf/LogSearchWebServerCustomizer.java
  ambari-logsearch-server/src/main/resources/log4j2.yml
Labels: enhancement

#39 [AMBARI-24945] [Log Search UI] Handling null or undefined value in log's level property.
  ambari-logsearch-web/src/app/components/log-level/log-level.component.html
  ambari-logsearch-web/src/app/components/log-level/log-level.component.spec.ts
  ambari-logsearch-web/src/app/components/service-logs-table/service-logs-table.component.html
Labels: web

#40 AMBARI-24949. Log Search: add Solr node discovery + small cleanups
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/common/LogFeederConstants.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/common/LogFeederSolrClientFactory.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/ApplicationConfig.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/LogFeederProps.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputSolr.java
  ambari-logsearch-logfeeder/src/test/java/org/apache/ambari/logfeeder/common/LogFeederSolrClientFactoryTest.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/conf/LogSearchConfigApiConfig.java
  ambari-logsearch-server/src/main/resources/logsearch.properties
  docker/test-config/logsearch/logsearch.properties
  jenkins/containers/docker-logsearch-portal/conf/logsearch.properties
Labels: cleanup, enhancement

#41 AMBARI-24950 - Logsearch: use os timezone in Logfeeder
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/loglevelfilter/LogLevelFilterHandler.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/util/DateUtil.java
Labels: bug, cleanup

#42 AMBARI-24956. Log Search: cleanup audit/service log config name prefixes
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/conf/SolrAuditLogPropsConfig.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/conf/SolrMetadataPropsConfig.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/conf/SolrServiceLogPropsConfig.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/dao/SolrSchemaFieldDao.java
  ambari-logsearch-server/src/main/resources/logsearch.properties
  ambari-logsearch-server/src/test/resources/logsearch.properties
  docker/test-config/logsearch/logsearch-https.properties
  docker/test-config/logsearch/logsearch-sso.properties
  docker/test-config/logsearch/logsearch.properties
  jenkins/containers/docker-logsearch-portal/conf/logsearch.properties
Labels: cleanup

#44 AMBARI-24959. Log Search: show log level filters are enabled or disabled on /info/features endpoint
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/common/LogSearchConstants.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/manager/InfoManager.java
Labels: enhancement

#45 Cleanup metadata: remove/rename event history references
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/converter/EventHistoryRequestQueryConverter.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/converter/MetadataRequestQueryConverter.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/health/SolrMetadataHealthIndicator.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/manager/MetadataManager.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/model/request/MetadataParamDefinition.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/model/request/impl/MetadataRequest.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/model/request/impl/query/MetadataQueryRequest.java
  ambari-logsearch-server/src/test/java/org/apache/ambari/logsearch/converter/MetadataRequestQueryConverterTest.java
Labels: cleanup

#46 AMBARI-24662. Support non-plain text passwords for LDAP authentication
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/conf/LogSearchLdapAuthConfig.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/conf/SecurityConfig.java
Labels: enhancement

#47 AMBARI-24939. Refactor logsearch_metadata schema and usage for logsearch portal
  ambari-logsearch-config-solr/src/main/java/org/apache/ambari/logsearch/config/solr/LogLevelFilterManagerSolr.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/common/LogFeederConstants.java
  ambari-logsearch-server/src/main/configsets/logsearch_metadata/conf/managed-schema
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/common/LogSearchConstants.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/converter/MetadataRequestQueryConverter.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/dao/MetadataSolrDao.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/doc/DocConstants.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/manager/MetadataManager.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/model/request/MetadataParamDefinition.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/model/request/impl/MetadataRequest.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/model/request/impl/query/MetadataQueryRequest.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/model/response/LogSearchMetaDataListResponse.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/model/response/LogsearchMetaData.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/rest/MetadataResource.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/solr/SolrConstants.java
  ambari-logsearch-server/src/test/java/org/apache/ambari/logsearch/converter/MetadataRequestQueryConverterTest.java
Labels: cleanup, enhancement

#43 [AMBARI-24900] [Log Search UI] Display the number of selection for the multiple selection dropdowns
  ambari-logsearch-web/src/app/components/menu-button/menu-button.component.html
  ambari-logsearch-web/src/app/components/menu-button/menu-button.component.less
  ambari-logsearch-web/src/app/components/menu-button/menu-button.component.ts
  ambari-logsearch-web/src/app/modules/shared/components/dropdown-button/dropdown-button.component.html
  ambari-logsearch-web/src/app/modules/shared/components/dropdown-button/dropdown-button.component.less
  ambari-logsearch-web/src/app/modules/shared/components/dropdown-button/dropdown-button.component.ts
  ambari-logsearch-web/src/app/modules/shared/variables.less
Labels: web

#49 AMBARI-24833. ABFS (ADLS v2) fs implementation was not included on the classpath
  ambari-logsearch-logfeeder/src/main/resources/core-site-examples/abfs-core-site.xml
  ambari-logsearch-logfeeder/src/main/resources/core-site-examples/s3-core-site.xml
  ambari-logsearch-logfeeder/src/main/resources/core-site-examples/wasb-core-site.xml
  pom.xml
Labels: bug

#50 [AMBARI-24975] Log Search UI: if there are multiple clusters - selecting one of it does not do anything
  ambari-logsearch-web/src/app/modules/shared/components/dropdown-list/dropdown-list.component.html
  ambari-logsearch-web/src/app/modules/shared/components/dropdown-list/dropdown-list.component.ts
Labels: web
