Repository apache/ambari-logsearch, pull requests merged in 2018-10, with the labels that each got.

#3 AMBARI-24739. Add support to JDK8 build by makefile and add contribution guide to Log Search
  Makefile
  README.md
Labels: documentation

#6 AMBARI-24746. Upgrade Solr version to 7.5.0
  ambari-logsearch-server/src/main/configsets/audit_logs/conf/solrconfig.xml
  ambari-logsearch-server/src/main/configsets/hadoop_logs/conf/solrconfig.xml
  ambari-logsearch-server/src/main/configsets/history/conf/solrconfig.xml
  docker/Dockerfile
  docker/docker-compose.yml
  docker/logsearch-docker.sh
  docker/solr.yml
  docker/sso.yml
  pom.xml
Labels: enhancement

#7 AMBARI-24692. Use jdk8 as default compiler version
  Makefile
  ambari-logsearch-logfeeder/src/main/scripts/logfeeder.sh
  ambari-logsearch-server/src/main/scripts/logsearch.sh
  pom.xml
Labels: cleanup

#9 AMBARI-24789. LogFeeder: fix CVE-2018-11771 - upgrade commons-compress lib
  ambari-logsearch-logfeeder/pom.xml
Labels: security

#10 AMBARI-24802 - Logsearch: upgrade swagger-ui to 3.19.0
  ambari-logsearch-server/pom.xml
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/common/ApiDocStorage.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/rest/AuditLogsResource.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/rest/EventHistoryResource.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/rest/ServiceLogsResource.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/rest/ShipperConfigResource.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/rest/StatusResource.java
  ambari-logsearch-server/src/main/resources/swagger/swagger.html
Labels: enhancement, web

#11 Update maven versioning
  Makefile
  README.md
  ambari-logsearch-appender/pom.xml
  ambari-logsearch-assembly/pom.xml
  ambari-logsearch-config-api/pom.xml
  ambari-logsearch-config-json/pom.xml
  ambari-logsearch-config-local/pom.xml
  ambari-logsearch-config-solr/pom.xml
  ambari-logsearch-config-zookeeper/pom.xml
  ambari-logsearch-it/pom.xml
  ambari-logsearch-log4j2-appender/pom.xml
  ambari-logsearch-logfeeder-container-registry/pom.xml
  ambari-logsearch-logfeeder-plugin-api/pom.xml
  ambari-logsearch-logfeeder/pom.xml
  ambari-logsearch-server/pom.xml
  ambari-logsearch-web/pom.xml
  pom.xml
Labels: enhancement

#12 Make rule to set version is `update-version`, not `set-version`
  README.md
Labels: documentation

#13 AMBARI-24825. Log Feeder: Fix HDFS/S3 outputs
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputFile.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputHDFSFile.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputS3File.java
  ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/spool/LogSpooler.java
  ambari-logsearch-logfeeder/src/main/scripts/logfeeder.sh
  ambari-logsearch-server/src/main/scripts/logsearch.sh
  docker/cloud-docker-compose.yml
  docker/test-config/logfeeder/shipper-conf/output.config.json
Labels: bug

#15 AMBARI-24851 - Logsearch: debug mode using java 8 and 11
  ambari-logsearch-server/src/main/scripts/logsearch.sh
Labels: bug
