Repository apache/ambari-logsearch, pull requests merged in 2019-01, with the labels that each got.

#65 AMBARI-25083. Fallback to use dynamic field 'ws_*' if new field name contains whitespace
  ambari-logsearch-logfeeder-plugin-api/src/main/java/org/apache/ambari/logfeeder/plugin/filter/Filter.java
Labels: bug

#66 AMBARI-23456. Add cloud mode documentation
  docs/cloud_mode.md
Labels: documentation

#68 AMBARI-23456. Add developement guide markdowns & remove some old docs
  README.md
  ambari-logsearch-logfeeder/README.md
  ambari-logsearch-server/README.md
  docs/development.md
Labels: documentation

#67 [AMBARI-25028] [Log Search UI] Populate `Component Name` in validator
  ambari-logsearch-web/src/app/modules/shared/components/dropdown-button/dropdown-button.component.html
  ambari-logsearch-web/src/app/modules/shared/components/dropdown-button/dropdown-button.component.ts
  ambari-logsearch-web/src/app/modules/shared/components/filter-dropdown/filter-dropdown.component.spec.ts
  ambari-logsearch-web/src/app/modules/shared/components/filter-dropdown/filter-dropdown.component.ts
  ambari-logsearch-web/src/app/modules/shipper/components/shipper-configuration/shipper-configuration.component.spec.ts
  ambari-logsearch-web/src/app/modules/shipper/components/shipper-configuration/shipper-configuration.component.ts
  ambari-logsearch-web/src/app/modules/shipper/components/shipper-service-configuration-form/shipper-service-configuration-form.component.html
  ambari-logsearch-web/src/app/modules/shipper/components/shipper-service-configuration-form/shipper-service-configuration-form.component.less
  ambari-logsearch-web/src/app/modules/shipper/components/shipper-service-configuration-form/shipper-service-configuration-form.component.ts
  ambari-logsearch-web/src/app/modules/shipper/directives/validator.directive.ts
Labels: web

#69 AMBARI-23456. Make rest api doc generation configureable & doc fixes
  Makefile
  ambari-logsearch-docs/pom.xml
  ambari-logsearch-docs/src/main/java/org/apache/ambari/logsearch/doc/LogSearchDocumentationGenerator.java
  ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/rest/ServiceLogsResource.java
  docs/api-docs/logsearch-swagger.yaml
Labels: documentation

#70 AMBARI-25090 - Logsearch should index keywords without the ending periods(.)
  ambari-logsearch-it/src/test/java/org/apache/ambari/logsearch/solr/search/SearchServiceLogsTest.java
  ambari-logsearch-server/src/main/configsets/audit_logs/conf/managed-schema
  ambari-logsearch-server/src/main/configsets/hadoop_logs/conf/managed-schema
Labels: bug
